version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./dataset:/study/insider_threat_system/dataset
      - ./ml_model:/study/insider_threat_system/ml_model

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend